Repository s-owl/skhu-app, pull requests merged in 2019-09, with the labels that each got.

#90 [feature/update-before-display] 시간표, 출결 데이터 먼저 갱신 후 표시
  src/screens/attendance.js
  src/screens/studentTimetable.js
Labels: feature

#92 교원별 시간표 조회기능 구현
  src/MainShell.js
  src/Menu.js
  src/components/Timetable.js
  src/screens/counsel.js
  src/screens/notice.js
  src/screens/professorTimetable.js
  src/screens/syllabus.js
  src/screens/syllabusDetails.js
  src/tools/apis.js
  src/tools/dbhelper.js
Labels: feature

#101 강의실별 시간표 조회기능 구현
  src/MainShell.js
  src/Menu.js
  src/screens/lectureRoomTimetable.js
  src/tools/apis.js
Labels: feature

#109 [hotfix/pw-change] 비번 변경 시 로그인 정보를 입력 못 해 로그인에서 무한루프하는 현상
  src/components/errorModal.js
Labels: bug

#110 OTA 버전 변경
  src/config.js
Labels: deploy

#112 디자인 업데이트
  src/Login.js
  src/Main.js
  src/Menu.js
  src/components/Timetable.js
  src/components/components.js
  src/components/errorModal.js
  src/components/helpModal.js
  src/components/infoModal.js
  src/components/listitem.js
  src/components/searchBar.js
  src/components/summaryWidget.js
  src/components/touchable.js
  src/components/weather.js
  src/screens/about.js
  src/screens/attendance.js
  src/screens/counsel.js
  src/screens/credits.js
  src/screens/gradeCert.js
  src/screens/lectureRoomTimetable.js
  src/screens/meal.js
  src/screens/notice.js
  src/screens/professorTimetable.js
  src/screens/savedCredits.js
  src/screens/schedules.js
  src/screens/scholarshopHistory.js
  src/screens/searchCondition.js
  src/screens/subjects.js
  src/screens/syllabus.js
  src/screens/syllabusDetails.js
  src/tools/apis.js
  src/tools/dbhelper.js
Labels: enhancement

#113 인증정보 화면 및 PIN/생체 인증 화면 추가
  app.json
  package.json
  src/Main.js
  src/MainShell.js
  src/Menu.js
  src/components/localauth.js
  src/components/touchable.js
  src/screens/authinfo.js
  yarn.lock
Labels: feature

#116 0.3.0 배포 준비
  app.json
  assets/imgs/profilePlaceholder.png
  package.json
  src/Login.js
  src/Main.js
  src/MainShell.js
  src/Menu.js
  src/components/Timetable.js
  src/components/components.js
  src/components/errorModal.js
  src/components/helpModal.js
  src/components/infoModal.js
  src/components/listitem.js
  src/components/localauth.js
  src/components/searchBar.js
  src/components/summaryWidget.js
  src/components/touchable.js
  src/components/weather.js
  src/screens/about.js
  src/screens/attendance.js
  src/screens/authinfo.js
  src/screens/counsel.js
  src/screens/credits.js
  src/screens/gradeCert.js
  src/screens/lectureRoomTimetable.js
  src/screens/meal.js
  src/screens/notice.js
  src/screens/professorTimetable.js
  src/screens/savedCredits.js
  src/screens/schedules.js
  src/screens/scholarshopHistory.js
  src/screens/searchCondition.js
  src/screens/settings.js
  src/screens/subjects.js
  src/screens/syllabus.js
  src/screens/syllabusDetails.js
  src/tools/apis.js
  src/tools/dbhelper.js
  yarn.lock
Labels: deploy
